[tool.poetry]
name = "app-api"
version = "1.1.4"
description = "A simple ex of py api"
authors = ["OSX-RSPlug-a <log-n@outlook.com>"]
license = "BSD"
readme = "README.md"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
